### ISSUE TITLE
Works on frigate 0.14.0

### ISSUE THREAD

**Issue by frantathefranta** [bairhys/prometheus-frigate-exporter#14]
Hey, just installed this on frigate 0.14.0 and it works perfectly. Just raising this issue so the README can be updated.

**Comment by bairhys** [comment]
Hi @frantathefranta, 

Yeah it has been working well for me too during the 0.14.0 betas. 

I was getting in Grafana a weird CPU and MEM item in Grafana labeled ` | | `. Looks like in 0.14.0 a new `frigate.full_system` CPU and MEM value is being exported. In Grafana, I filtered out `frigate.full_system` and uploaded a new dashboard revision to Grafana Labs.

Before I filtered out `frigate.full_system`


![image](https://github.com/user-attachments/assets/837b5003-24bf-4cda-8fc7-4b902b0b368c)

After

![image](https://github.com/user-attachments/assets/c83c3621-f876-49ba-abf2-a13cecdce18c)
