### ISSUE TITLE
CPU usage in Mem Usage chart

### ISSUE THREAD

**Issue by IAmKonni** [bairhys/prometheus-frigate-exporter#15]
Hi,

i imported your prepared grafana dashboard via https://grafana.com/grafana/dashboards/18226-frigate/ and I found an error in one of the queries.
In the Memory Usage chart is a reference to cpu usage, which should be mem usage. You need to replace cpu by mem in this query:

![image](https://github.com/user-attachments/assets/04421251-034e-43be-939d-b3269b87f051)

Thank you for your really nice and helpful tool. :)

Best wishes
Konni

**Comment by bairhys** [comment]
Hi @IAmKonni ,

I have updated the dashboard with your fix at https://grafana.com/grafana/dashboards/18226-frigate/

Thanks for finding this issue and letting me know!
