### ISSUE TITLE
0.15 Events no longer include sublabels

### ISSUE THREAD

**Issue by YenLegion** [bairhys/prometheus-frigate-exporter#16]
On the 0.15 dev version where the event view used to include sublabels, now only includes labels i.e. car, person.

**Comment by bairhys** [comment]
Hey, I updated to Frigate 0.15.0-beta1 and my exporter is working ok so far. Do you see a particular issue?

**Comment by YenLegion** [comment]
Nvm. Is working, not sure what changed.
