### ISSUE TITLE
MiB 5k proc CPU usage

### ISSUE THREAD

**Issue by PovilasID** [bairhys/prometheus-frigate-exporter#2]
Hey, 
thanks for awesome exporter, I ran it and got: `frigate_cpu_usage_percent{pid="MiB"} 5613.0`
I was happy to see my processor can turbot o 5000% 🚀 🤣  but little worried too.
Here is my htop:
![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/396243/c9066e91-86f5-4395-903d-f8fbdebdc72a)
There is MiB under CPU usageprovided by /api/stats
```
"MiB": {
"cpu": "5614.3",
"mem": "avail"
},
```
I think it some kind of an average over time or lost pram not sure it should go to frigate or here.
My frigate version: Frigate (0.12.0-da3e197)

**Comment by bairhys** [comment]
Hi @PovilasID, great to hear you like the exporter 👍

Could you post your Frigate CPU usage graph? I'm curious what it looks like

**Comment by PovilasID** [comment]
If MiB is not filtered it looks like this:
![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/396243/acc4220f-fa19-455a-937a-2157f238fe63)
Is this what you meant?

**Comment by bairhys** [comment]
Yep that's the graph. Yeah it is not very insightful. I'm not sure why this is happening but looks to be a Frigate API issue sending wrong data?

It is also interesting you have `MiB` instead of the pid number (you can see my exporter output on the readme)

You could filter out "MiB" in grafana like this (but sounds like you might be doing already). Could add `, pid!="MiB"` to the graph query like this to remove it:

![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/33058425/62b3e753-4cd2-4eaf-81df-c7732bda8159)

**Comment by PovilasID** [comment]
Yup I did exactly that with the gauge up top and this graph.
I am starting to suspect that this is a side effect of how frigate scrapes system data and my host OS being OpenWRT. It is a router OS and when I google MiB in relation to CPU it looked like it showed up in networking system prams for networking equipment.

**Comment by bairhys** [comment]
Wow that's cool you have it running on OpenWRT. 

I use OpenWRT too but on my wifi router and Ubuntu for my server that has Frigate, this exporter, Prometheus & Grafana.

**Comment by PovilasID** [comment]
It is not cool... it's very janky. However, it is both a router and NVR in one box, so I am quite happy about that. 
This is setup for my garden, so I am running the exporter on a remote server using some mech networks to access the stats page. 
I think we can close this as solution seams to be outside of the scope for this project :)

**Comment by SpangleLabs** [comment]
I'm seeing this same issue btw, but running Frigate (and the exporter) on Ubuntu inside a docker image

**Comment by SpangleLabs** [comment]
Ah, trying to search frigate's github for similar issues is.. tricky, because almost every issue has a dump of the stats endpoint, which includes these false entries

**Comment by bairhys** [comment]
@SpangleLabs How long have you ran this exporter? Has it only just started showing high cpu or have you only just started using the exporter?

**Comment by SpangleLabs** [comment]
> @SpangleLabs How long have you ran this exporter? Has it only just started showing high cpu or have you only just started using the exporter?

I had literally just spun up the exporter and immediately it shows all those, as the exporter is just mirroring the stats from Frigate's stats endpoint I guess.
I filed a ticket on Frigate's side for it, as that's clearly a bug on their end: https://github.com/blakeblackshear/frigate/issues/9373
