### ISSUE TITLE
Some missing stats w Latest Frigate (ie v13 beta5) (per camera stats missing) - possible JSON change on /api/stats

### ISSUE THREAD

**Issue by bob454522** [bairhys/prometheus-frigate-exporter#3]
First off thank you very much for making this public - this is not something you had to do and I very much appreciate it!

I'm pretty sure the format of the JSON outputted by frigate at: /api/stats has changed as of V13 Beta5  (ie: frigate:0.13.0-beta5  -  in this case im running the very latest:  frigate:dev-18062ec )   I'm not in a position to run frigate v12 right now to confirm my theory.  

however from what I can tell in looking at other forum posts , it looks like a new JSON root/ parent was added named “cameras” so now the json path is:  **Cameras.**frontDoorCam.camera_fps.5  where as before the json path was just  frontDoorCam.camera_fps.5

![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/60830628/477c5ec4-5dc5-49c7-9920-f16e17b21565)

All other stats are working / being pulled int by your python exporter,  except the cameras (due to this new format i assume).

I unfortunately don't have the python skills to adjust for this change so wanted to bring it to your attention. If it were something easy like a name change I would add a PR, but I'm not sure how to add json parsing of a new root / parent tree (cameras.*) to your python code.  

thanks

grafana / prom snips:

![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/60830628/77664300-a698-415d-b7cf-9bc0fad69c36)

![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/60830628/2f19e318-d919-415f-914c-0ac85cc7073f)

**Comment by bairhys** [comment]
Hey thanks for bringing this up. I updated to v13 beta5 during the week and haven't checked my stats til now and I am also having the same issues. I'll let you know when I fix it. My camera, cpu and memory stats are not showing the same data as 12.

These are before and after 12 to 13beta5
![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/33058425/768684b0-8dcd-4671-a3cf-e52ba695d230)
![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/33058425/60833087-1c0f-48e9-a8d2-9c0602668275)

**Comment by PovilasID** [comment]
I updated to 0.13 beta 6 today and saw the same problem.
I am no expert either but I looked at the code already there and made a fix that you can use. 
If you are super inpatient you can clone my repo and build the container yourself

**Comment by bob454522** [comment]
> I updated to 0.13 beta 6 today and saw the same problem. I am no expert either but I looked at the code already there and made a fix that you can use. If you are super inpatient you can clone my repo and build the container yourself

Perfect!  thank you-  your solution works in my testing.
  in my case i just edited the container and added/changed your 2x lines:

ie: 
`docker exec -it 3fc72b06359a sh`
then `vi /var/python_scripts/prometheus_frigate_exporter.py`

and modified the python to include your changes:  https://github.com/bairhys/prometheus-frigate-exporter/compare/main...PovilasID:prometheus-frigate-exporter:main
(and then restart the container) -> now all stats are being retreived!

**Comment by bairhys** [comment]
I merged @PovilasID changes and made it work with 0.12 and 0.13 beta 5. The docker hub image has also updated. 

The updated exporter tests ok for me on 0.12 and 0.13 beta 5.

Can see below (detection fps not so clear) that the middle data (frigate 0.12) and end data (frigate 0.13 beta 5) have a similar amount of data series. Let me know if it doesn't work for you.

![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/33058425/eca8b39d-f083-4247-8429-031084a31f21)

![image](https://github.com/bairhys/prometheus-frigate-exporter/assets/33058425/08221bc4-5a5b-471e-920d-a77107472e28)
