### ISSUE TITLE
Docker ARM build

### ISSUE THREAD

**Issue by PovilasID** [bairhys/prometheus-frigate-exporter#6]
Hey,

I am running my monitoring on ARM based machine, so I have to build this from source.
It would be cool if you used github actions to build docker containers for both architectures.
Here is sample form one of my repos: https://github.com/PovilasID/P110-Exporter/blob/master/.github/workflows/docker-image.yml
I am no expert docker maintainer but it works and it's not complicated.
You would need to get docker hub API keys and ad them to this repo's secrets (there are plenty of tutorials on that) or you can use GitHub's built int release container registry building but that would require to change image definition for existing users.

**Comment by bairhys** [comment]
Thanks for the suggestion and example. This is definitely on my todo list, I might get some time soon to set it up.

**Comment by bairhys** [comment]
I have set up Github Actions to build and push to Docker Hub for platforms `linux/amd64,linux/arm64`. Thanks for your sample, it helped a lot.
