### ISSUE TITLE
Number of decimal places for inference time

### ISSUE THREAD

**Issue by 1Kris** [bairhys/prometheus-frigate-exporter#8]
It appears as though the Frigate API is showing inference time as milliseconds with two decimal places, like:
"inference_speed": 6.79,

However, the exporter is showing it as seconds, with insufficient decimal places.  
frigate_detector_inference_speed_seconds{name="coral1"} 0.007

It would be helpful to add two more decimal places to that value so we can see proper data granularity.  

I see similar is true for Device Temperature, GPU Utilization, maybe others.  

This is a great tool, thank you for that, and for your support with this.

**Comment by 1Kris** [comment]
It looks fabulous now, thanks!  You can close this as you wish of course.  

I see you didn't skimp on the digits.  
frigate_detector_inference_speed_seconds{name="coral1"} 0.007019999999999999

It is interesting that Frigate Other Processes memory utilization jumped from 4.5% to 7.3% coincident with the change.  Nothing big, but surprising that it changed at all.  

My only other desire may be a Mean line for Inference time, but I am not sure that it is feasible.

**Comment by bairhys** [comment]
That's great. I didn't notice the numbers were not getting read fully until you mentioned it so thanks for that! Much better now.

It is easy to add a mean line in Grafana. Need to add a new query dataset to the inference graph: `avg_over_time(frigate_detector_inference_speed_seconds[30m])`. This does a rolling average over 30mins.  Or actually I have added a mean line for the inference speed to my dashboard. The updated dashboard is [here](https://grafana.com/grafana/dashboards/18226-frigate/).
